### ISSUE TITLE
麻烦博主帮忙看一下，英文数据训练问题

### ISSUE THREAD

**Issue by Atom-J** [wzzzd/lm_ner#22]
使用英文数据集训练出现如下错误，看了好久不知道怎么解决：
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    trainer.train()
  File "F:\Files\lm_ner-main\process\Trainer.py", line 220, in train
    loss = self.step(bs)
  File "F:\Files\lm_ner-main\process\Trainer.py", line 248, in step
    outputs = self.model(input_ids, labels=labels, attention_mask=attention_mask)   #
  File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\biyesheji\lm_ner-main\model\transformer_crf.py", line 52, in forward
    loss = -1 * self.crf(emissions = logits, tags=labels, mask=attention_mask)
  File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\Files\lm_ner-main\model\layers\crf.py", line 100, in forward
    numerator = self._compute_score(emissions, tags, mask)
  File "F:\Files\lm_ner-main\model\layers\crf.py", line 213, in _compute_score
    last_tags = tags[seq_ends, torch.arange(batch_size)]
IndexError: index 1065 is out of bounds for dimension 0 with size 256

**Comment by Atom-J** [comment]
还有一个问题，如果使用英文数据集的话是每个单词一个标签还是每个字母一个标签啊

**Comment by wzzzd** [comment]
> 还有一个问题，如果使用英文数据集的话是每个单词一个标签还是每个字母一个标签啊

一个单词一个标签的

**Comment by wzzzd** [comment]
> 使用英文数据集训练出现如下错误，看了好久不知道怎么解决： Traceback (most recent call last): File "run.py", line 42, in trainer.train() File "F:\Files\lm_ner-main\process\Trainer.py", line 220, in train loss = self.step(bs) File "F:\Files\lm_ner-main\process\Trainer.py", line 248, in step outputs = self.model(input_ids, labels=labels, attention_mask=attention_mask) # File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "F:\biyesheji\lm_ner-main\model\transformer_crf.py", line 52, in forward loss = -1 * self.crf(emissions = logits, tags=labels, mask=attention_mask) File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "F:\Files\lm_ner-main\model\layers\crf.py", line 100, in forward numerator = self._compute_score(emissions, tags, mask) File "F:\Files\lm_ner-main\model\layers\crf.py", line 213, in _compute_score last_tags = tags[seq_ends, torch.arange(batch_size)] IndexError: index 1065 is out of bounds for dimension 0 with size 256

看着像句子长度超过Config.py文件里面配置的max_seq_length的长度了

**Comment by Atom-J** [comment]
> > 使用英文数据集训练出现如下错误，看了好久不知道怎么解决： Traceback (most recent call last): File "run.py", line 42, in trainer.train() File "F:\Files\lm_ner-main\process\Trainer.py", line 220, in train loss = self.step(bs) File "F:\Files\lm_ner-main\process\Trainer.py", line 248, in step outputs = self.model(input_ids, labels=labels, attention_mask=attention_mask) # File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "F:\biyesheji\lm_ner-main\model\transformer_crf.py", line 52, in forward loss = -1 * self.crf(emissions = logits, tags=labels, mask=attention_mask) File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "F:\Files\lm_ner-main\model\layers\crf.py", line 100, in forward numerator = self._compute_score(emissions, tags, mask) File "F:\Files\lm_ner-main\model\layers\crf.py", line 213, in _compute_score last_tags = tags[seq_ends, torch.arange(batch_size)] IndexError: index 1065 is out of bounds for dimension 0 with size 256
> 
> 看着像句子长度超过Config.py文件里面配置的max_seq_length的长度了

非常感谢您的回答！

**Comment by Atom-J** [comment]
> > 使用英文数据集训练出现如下错误，看了好久不知道怎么解决： Traceback (most recent call last): File "run.py", line 42, in trainer.train() File "F:\Files\lm_ner-main\process\Trainer.py", line 220, in train loss = self.step(bs) File "F:\Files\lm_ner-main\process\Trainer.py", line 248, in step outputs = self.model(input_ids, labels=labels, attention_mask=attention_mask) # File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "F:\biyesheji\lm_ner-main\model\transformer_crf.py", line 52, in forward loss = -1 * self.crf(emissions = logits, tags=labels, mask=attention_mask) File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "F:\Files\lm_ner-main\model\layers\crf.py", line 100, in forward numerator = self._compute_score(emissions, tags, mask) File "F:\Files\lm_ner-main\model\layers\crf.py", line 213, in _compute_score last_tags = tags[seq_ends, torch.arange(batch_size)] IndexError: index 1065 is out of bounds for dimension 0 with size 256
> 
> 看着像句子长度超过Config.py文件里面配置的max_seq_length的长度了

但是我的数据集里面没有句子的长度超过512，并且我尝试使用conll2003的数据集后报了同样的错误
数据集样例：
EU B-ORG
rejects O
German B-MISC
call O
to O
boycott O
British B-MISC
lamb O
. O

Peter B-PER
Blackburn I-PER

BRUSSELS B-LOC
1996-08-22 O

The O
European B-ORG
Commission I-ORG
said O
on O
Thursday O
it O
disagreed O
with O
German B-MISC
advice O
to O
consumers O
to O
shun O
British B-MISC
lamb O
until O
scientists O
determine O
whether O
mad O
cow O
disease O
can O
be O
transmitted O
to O
sheep O
. O
关于这个错误您是否还有其他思路？感谢

**Comment by wzzzd** [comment]
> > > 使用英文数据集训练出现如下错误，看了好久不知道怎么解决： Traceback (most recent call last): File "run.py", line 42, in trainer.train() File "F:\Files\lm_ner-main\process\Trainer.py", line 220, in train loss = self.step(bs) File "F:\Files\lm_ner-main\process\Trainer.py", line 248, in step outputs = self.model(input_ids, labels=labels, attention_mask=attention_mask) # File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "F:\biyesheji\lm_ner-main\model\transformer_crf.py", line 52, in forward loss = -1 * self.crf(emissions = logits, tags=labels, mask=attention_mask) File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "F:\Files\lm_ner-main\model\layers\crf.py", line 100, in forward numerator = self._compute_score(emissions, tags, mask) File "F:\Files\lm_ner-main\model\layers\crf.py", line 213, in _compute_score last_tags = tags[seq_ends, torch.arange(batch_size)] IndexError: index 1065 is out of bounds for dimension 0 with size 256
> > 
> > 
> > 看着像句子长度超过Config.py文件里面配置的max_seq_length的长度了
> 
> 但是我的数据集里面没有句子的长度超过512，并且我尝试使用conll2003的数据集后报了同样的错误 数据集样例： EU B-ORG rejects O German B-MISC call O to O boycott O British B-MISC lamb O . O
> 
> Peter B-PER Blackburn I-PER
> 
> BRUSSELS B-LOC 1996-08-22 O
> 
> The O European B-ORG Commission I-ORG said O on O Thursday O it O disagreed O with O German B-MISC advice O to O consumers O to O shun O British B-MISC lamb O until O scientists O determine O whether O mad O cow O disease O can O be O transmitted O to O sheep O . O 关于这个错误您是否还有其他思路？感谢

数据处理的逻辑，有改动过哪些地方么？

**Comment by Atom-J** [comment]
> > > > 使用英文数据集训练出现如下错误，看了好久不知道怎么解决： Traceback (most recent call last): File "run.py", line 42, in trainer.train() File "F:\Files\lm_ner-main\process\Trainer.py", line 220, in train loss = self.step(bs) File "F:\Files\lm_ner-main\process\Trainer.py", line 248, in step outputs = self.model(input_ids, labels=labels, attention_mask=attention_mask) # File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "F:\biyesheji\lm_ner-main\model\transformer_crf.py", line 52, in forward loss = -1 * self.crf(emissions = logits, tags=labels, mask=attention_mask) File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "F:\Files\lm_ner-main\model\layers\crf.py", line 100, in forward numerator = self._compute_score(emissions, tags, mask) File "F:\Files\lm_ner-main\model\layers\crf.py", line 213, in _compute_score last_tags = tags[seq_ends, torch.arange(batch_size)] IndexError: index 1065 is out of bounds for dimension 0 with size 256
> > > 
> > > 
> > > 看着像句子长度超过Config.py文件里面配置的max_seq_length的长度了
> > 
> > 
> > 但是我的数据集里面没有句子的长度超过512，并且我尝试使用conll2003的数据集后报了同样的错误 数据集样例： EU B-ORG rejects O German B-MISC call O to O boycott O British B-MISC lamb O . O
> > Peter B-PER Blackburn I-PER
> > BRUSSELS B-LOC 1996-08-22 O
> > The O European B-ORG Commission I-ORG said O on O Thursday O it O disagreed O with O German B-MISC advice O to O consumers O to O shun O British B-MISC lamb O until O scientists O determine O whether O mad O cow O disease O can O be O transmitted O to O sheep O . O 关于这个错误您是否还有其他思路？感谢
> 
> 数据处理的逻辑，有改动过哪些地方么？
感谢您的提醒，我之前确实对DataManager文件做了修改，改回后已经可以顺利开始训练，再次感谢您的耐心回复

**Comment by wzzzd** [comment]
不客气 ;)

**Comment by guoluqingfeng10086** [comment]
> > > > > 使用中文数据集训练出现如下错误，看了好久不知道怎么解决： Traceback (most最近一次调用最后): File "run.py", line 42, in trainer.train() File "F:\Files\lm_ner- main\process\Trainer.py”，第 220 行，在训练中 loss = self.step(bs) 文件“F:\Files\lm_ner-main\process\Trainer.py”，第 248 行，在步骤输出中= self.model(input_ids, labels=labels, Attention_mask=attention_mask) # 文件“F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py”，第 1518 行，在 _wrapped_call_impl 返回 self._call_impl(*args, **kwargs) 文件“F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py”，第 1527 行，在 _call_impl 中返回 forward_call(*args, **kwargs) 文件“F: \biyesheji\lm_ner-main\model\transformer_crf.py”，第 52 行，前向损失 = -1 * self.crf（emissions = logits，tags=labels，mask=attention_mask）文件“F:\software_of_computer_learning\Anaconda\install_path \envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py”，第 1518 行，在 _wrapped_call_impl 中返回 self._call_impl(*args, **kwargs) 文件“F:\software_of_computer_learning\Anaconda\install_path\envs\Bert_BiLstm\lib\site-packages\torch\nn\modules\module.py”，第 1527 行，在 _call_impl 中返回 forward_call(*args, **kwargs) 文件“F: \Files\lm_ner-main\model\layers\crf.py”，第 100 行，正向分子 = self._compute_score(emissions, tags, mask) 文件“F:\Files\lm_ner-main\model\layers\crf。 py”，第 213 行，位于 _compute_score last_tags = tags[seq_ends, torch.arange(batch_size)] IndexError: 索引 1065 超出了大小为 256 的维度 0 的范围
> > > > 
> > > > 
> > > > 看句子像长度超过Config.py文件里面配置的max_seq_length的长度了
> > > 
> > > 
> > > 但是我的数据集里面句子的长度超过512，并且我尝试使用conll2003的数据集后报了同样的错误数据集样例：EU B-ORG拒绝O德国B-MISC呼吁O对O抵制O英国B -MISC 羊肉 O 。 O 
> > > Peter B-PER Blackburn I-PER 
> > > BRUSSELS B-LOC 1996-08-22 O
> > > 欧洲 B-ORG 委员会 I-ORG 于 O 星期四表示 O 不同意 O 与 O 德国 B-MISC 建议 O 对 O 消费者O 转 O 顺 O 英国 B-MISC 羔羊 O 直到 O 科学家 O 确定 O 是否 O 发疯 O 牛 O 疾病 O 可以 O 传播 O 给 O 羊 O 。关于此错误您是否还有其他解决办法？谢谢
> > 
> > 
> > 数据处理的逻辑，有经过哪些地方吗？
> > 谢谢您的提醒，我之前确实对DataManager文件做好了，改回后已经可以顺利修改开始训练，再次感谢您的耐心回复

请问英文数据集用的预训练模型选哪个呢

**Comment by wzzzd** [comment]
Config.py文件修改这两变量

language = 'en'
model_pretrain_online_checkpoint = 'bert-base-uncased'
